import type { Metadata } from "next";
import "./globals.css";
import './font.css'
import Navbar from "@/components/LandingPage/Navbar";
import Footer from "./section/Footer";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Akai Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar />
        {children}
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
